END_OF_QUEUE = None

#text type
TYPE_CEO = 'C'
TYPE_ANALYST = 'A'
TYPE_JOURNALIST = 'J'
TYPE_DOT = '.'

#word dict
NUM_OF_WORD_TYPE = 5

WORD_FILTER = 0

#Self extracted Dictionary
WORD_CAUSE_IN = 1
WORD_CAUSE_EX = 2

WORD_CONTROL_LOW = 3
WORD_CONTROL_HIGH = 4

WORD_UNCERTAIN = 5

#McDonald Dictionary
MCD_LITIGIOUS = -1
MCD_UNCERTAIN = -2

MCD_MODAL_STRONG = -3
MCD_MODAL_WEAK = -4

MCD_NEG = -5
MCD_POS = -6

#NLTK lemmatizer
ADJ, ADV, NOUN, VERB = 'a', 'r', 'n', 'v'

#Topic model algorithm
ALGORITHM_LSI = 0
ALGORITHM_LDA = 1

MODE_BASIC = 0
MODE_POS_ANALYZE = 1

FUNC_TOPIC_MODEL_SPEAKER_ANALYST = 0
FUNC_TOPIC_MODEL_CONFERENCE_ANALYST = 1