TYPE_CEO = 'C'
TYPE_ANALYST = 'A'
TYPE_JOURNALIST = 'J'
TYPE_NONE = '.'


WORD_FILTER = 0

ALGORITHM_LSI = 0
ALGORITHM_LDA = 1

MODE_BASIC = 0
MODE_POS_ANALYZE = 1

THREAD_POOL_SIZE = 1

END_OF_QUEUE = None

FUNC_TOPIC_MODEL_SPEAKER_ANALYST = 0
FUNC_TOPIC_MODEL_CONFERENCE_ANALYST = 1